## preview_data

Here we'll loop over all the GTFS files and load them into a [pandas](https://pandas.pydata.org/about.html) dataframe
so we can see what the data looks like.

In [1]:
import os

import pandas

In [11]:
data_directory = '../data/ST-GTFS'

files = []
for filename in os.listdir(data_directory):
    if filename.endswith(".txt") or filename.endswith(".csv"):
        filepath = os.path.join(data_directory, filename)
        print(filepath)
        files.append(filepath)
        continue

../data/ST-GTFS/fare_attributes.txt
../data/ST-GTFS/timepoints.txt
../data/ST-GTFS/stop_attributes.txt
../data/ST-GTFS/agency.txt
../data/ST-GTFS/fare_rules.txt
../data/ST-GTFS/calendar_dates.txt
../data/ST-GTFS/stop_times.txt
../data/ST-GTFS/shapes.txt
../data/ST-GTFS/trips.txt
../data/ST-GTFS/stops.txt
../data/ST-GTFS/realtime_trips.txt
../data/ST-GTFS/calendar_attributes.txt
../data/ST-GTFS/realtime_routes.txt
../data/ST-GTFS/calendar.txt
../data/ST-GTFS/realtime_directions.txt
../data/ST-GTFS/routes.txt

In [16]:
len(files)

16

In [19]:
filepath = files[0]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/fare_attributes.txt

,fare_id,price,currency_type,payment_method,transfers,transfer_duration
0,OW_Adult_20160110,2.25,USD,0,0,NaN
1,OW_LocExp_20160110,4.00,USD,0,0,NaN

In [20]:
filepath = files[1]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/timepoints.txt

                        trip_id  stop_id
0      9898121-125-A-Weekday-50   315608
1      9898121-125-A-Weekday-50   315003
2      9898121-125-A-Weekday-50   315035
3      9898121-125-A-Weekday-50   315033
4      9898121-125-A-Weekday-50   315617
5      9898121-125-A-Weekday-50   315614
6      9898121-125-A-Weekday-50   315040
7      9898121-125-A-Weekday-50   315609
8      9898121-125-A-Weekday-50   314012
9      9898121-125-A-Weekday-50   314002
10     9898121-125-A-Weekday-50   314901
11     9898121-125-A-Weekday-50   313011
12     9898121-125-A-Weekday-50   313604
13     9898121-125-A-Weekday-50   312009
14     9898121-125-A-Weekday-50   311106
15     9898122-125-A-Weekday-50   315608
16     9898122-125-A-Weekday-50   315467
17     9898122-125-A-Weekday-50   315003
18     9898122-125-A-Weekday-50   315035
19     9898122-125-A-Weekday-50   315033
20     9898122-125-A-Weekday-50   315617
21     9898122-125-A-Weekday-50   315614
22     9898122-125-A-Weekday-50   315040
23     9898122-125-A-Weekday-50   315609
24     9898122-125-A-Weekday-50   314012
25     9898122-125-A-Weekday-50   314002
26     9898122-125-A-Weekday-50   314901
27     9898122-125-A-Weekday-50   313011
28     9898122-125-A-Weekday-50   313604
29     9898122-125-A-Weekday-50   312009
...                         ...      ...
51562   9917811-125-D-Sunday-50   332046
51563   9917812-125-D-Sunday-50   335639
51564   9917812-125-D-Sunday-50   311113
51565   9917812-125-D-Sunday-50   311093
51566   9917812-125-D-Sunday-50   311067
51567   9917812-125-D-Sunday-50   332111
51568   9917812-125-D-Sunday-50   332535
51569   9917812-125-D-Sunday-50   332263
51570   9917812-125-D-Sunday-50   332252
51571   9917812-125-D-Sunday-50   333508
51572   9917812-125-D-Sunday-50   332518
51573   9917812-125-D-Sunday-50   332184
51574   9917812-125-D-Sunday-50   332019
51575   9917812-125-D-Sunday-50   332544
51576   9917812-125-D-Sunday-50   332221
51577   9917812-125-D-Sunday-50   332348
51578   9917812-125-D-Sunday-50   332046
51579   9918203-125-D-Sunday-50   333510
51580   9918203-125-D-Sunday-50   334611
51581   9918204-125-D-Sunday-50   334612
51582   9918204-125-D-Sunday-50   334008
51583   9918205-125-D-Sunday-50   333510
51584   9918205-125-D-Sunday-50   334611
51585   9918206-125-D-Sunday-50   334612
51586   9918206-125-D-Sunday-50   334008
51587   9918207-125-D-Sunday-50   334612
51588   9918207-125-D-Sunday-50   333510
51589   9918208-125-D-Sunday-50   334008
51590   9918208-125-D-Sunday-50   334011
51591   9918208-125-D-Sunday-50   334611

[51592 rows x 2 columns]

In [21]:
filepath = files[3]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/agency.txt

,agency_name,agency_url,agency_timezone,agency_lang,agency_phone,agency_id
0,SamTrans,http://www.samtrans.com,America/Los_Angeles,en,800-660-4287,samtrans-ca-us

In [22]:
filepath = files[4]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/fare_rules.txt

               fare_id  route_id  origin_id  destination_id  contains_id
0    OW_Adult_20160110    14-158          1               1          NaN
1    OW_Adult_20160110    16-158          1               1          NaN
2    OW_Adult_20160110    17-158          1               1          NaN
3    OW_Adult_20160110    18-158          1               1          NaN
4    OW_Adult_20160110    19-158          1               1          NaN
5    OW_Adult_20160110    24-158          1               1          NaN
6    OW_Adult_20160110    25-158          1               1          NaN
7    OW_Adult_20160110    28-158          1               1          NaN
8    OW_Adult_20160110    29-158          1               1          NaN
9    OW_Adult_20160110    35-158          1               1          NaN
10   OW_Adult_20160110    37-158          1               1          NaN
11   OW_Adult_20160110    38-158          1               1          NaN
12   OW_Adult_20160110    39-158          1               1          NaN
13   OW_Adult_20160110    46-158          1               1          NaN
14   OW_Adult_20160110    49-158          1               1          NaN
15   OW_Adult_20160110    53-158          1               1          NaN
16   OW_Adult_20160110    54-158          1               1          NaN
17   OW_Adult_20160110    55-158          1               1          NaN
18   OW_Adult_20160110    56-158          1               1          NaN
19   OW_Adult_20160110    57-158          1               1          NaN
20   OW_Adult_20160110    58-158          1               1          NaN
21   OW_Adult_20160110    59-158          1               1          NaN
22   OW_Adult_20160110    60-158          1               1          NaN
23   OW_Adult_20160110    61-158          1               1          NaN
24   OW_Adult_20160110    62-158          1               1          NaN
25   OW_Adult_20160110    67-158          1               1          NaN
26   OW_Adult_20160110    68-158          1               1          NaN
27   OW_Adult_20160110    72-158          1               1          NaN
28   OW_Adult_20160110    73-158          1               1          NaN
29   OW_Adult_20160110    78-158          1               1          NaN
..                 ...       ...        ...             ...          ...
45   OW_Adult_20160110   122-158          1               1          NaN
46   OW_Adult_20160110   130-158          1               1          NaN
47   OW_Adult_20160110   140-158          1               1          NaN
48   OW_Adult_20160110   141-158          1               1          NaN
49   OW_Adult_20160110   250-158          1               1          NaN
50   OW_Adult_20160110   251-158          1               1          NaN
51   OW_Adult_20160110   256-158          1               1          NaN
52   OW_Adult_20160110   260-158          1               1          NaN
53   OW_Adult_20160110   270-158          1               1          NaN
54   OW_Adult_20160110   274-158          1               1          NaN
55   OW_Adult_20160110   275-158          1               1          NaN
56   OW_Adult_20160110   276-158          1               1          NaN
57   OW_Adult_20160110   278-158          1               1          NaN
58   OW_Adult_20160110   280-158          1               1          NaN
59   OW_Adult_20160110   281-158          1               1          NaN
60   OW_Adult_20160110   286-158          1               1          NaN
61   OW_Adult_20160110   292-158          1               1          NaN
62   OW_Adult_20160110   294-158          1               1          NaN
63   OW_Adult_20160110   295-158          1               1          NaN
64   OW_Adult_20160110   296-158          1               1          NaN
65   OW_Adult_20160110   397-158          1               1          NaN
66   OW_Adult_20160110   398-158          1               1          NaN
67   OW_Adult_20160110   399-158          1               1          NaN
68   OW_Adult_20160110   ECR-158          1               1          NaN
69   OW_Adult_20160110  FLXP-158          1               1          NaN
70   OW_Adult_20160110    KX-158          1               1          NaN
71   OW_Adult_20160110  SMCS-158          1               1          NaN
72  OW_LocExp_20160110   292-158          2               1          NaN
73  OW_LocExp_20160110   397-158          2               1          NaN
74  OW_LocExp_20160110    KX-158          2               1          NaN

[75 rows x 5 columns]

In [23]:
filepath = files[5]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/calendar_dates.txt

                        service_id      date  exception_type
0                 125-A-Weekday-50  20180528               2
1            125-A-Weekday-50-SDon  20180528               2
2    125-A-Weekday-50-SDon-1110100  20180528               2
3    125-A-Weekday-50-SDon-0101000  20180528               2
4            125-A-Weekday-50-SDon  20180219               2
5    125-A-Weekday-50-SDon-1110100  20180219               2
6    125-A-Weekday-50-SDon-0101000  20180219               2
7                  125-A-Sunday-50  20180528               1
8                 125-C-Weekday-50  20180528               2
9            125-C-Weekday-50-SDon  20180528               2
10   125-C-Weekday-50-SDon-0010000  20180528               2
11   125-C-Weekday-50-SDon-1110100  20180528               2
12   125-C-Weekday-50-SDon-0011000  20180528               2
13   125-C-Weekday-50-SDon-1101100  20180528               2
14   125-C-Weekday-50-SDon-0100000  20180528               2
15   125-C-Weekday-50-SDon-1100100  20180528               2
16   125-C-Weekday-50-SDon-1011100  20180528               2
17           125-C-Weekday-50-SDon  20180219               2
18   125-C-Weekday-50-SDon-0010000  20180219               2
19   125-C-Weekday-50-SDon-1110100  20180219               2
20   125-C-Weekday-50-SDon-0011000  20180219               2
21   125-C-Weekday-50-SDon-1101100  20180219               2
22   125-C-Weekday-50-SDon-0100000  20180219               2
23   125-C-Weekday-50-SDon-1100100  20180219               2
24   125-C-Weekday-50-SDon-1011100  20180219               2
25                 125-C-Sunday-50  20180528               1
26                125-D-Weekday-50  20180528               2
27   125-D-Weekday-50-SDon-1110100  20180528               2
28           125-D-Weekday-50-SDon  20180528               2
29   125-D-Weekday-50-SDon-1101100  20180528               2
..                             ...       ...             ...
120         125-D-Weekday-50-SDoff  20180507               2
121         125-D-Weekday-50-SDoff  20180508               2
122         125-D-Weekday-50-SDoff  20180509               2
123         125-D-Weekday-50-SDoff  20180510               2
124         125-D-Weekday-50-SDoff  20180511               2
125         125-D-Weekday-50-SDoff  20180514               2
126         125-D-Weekday-50-SDoff  20180515               2
127         125-D-Weekday-50-SDoff  20180516               2
128         125-D-Weekday-50-SDoff  20180517               2
129         125-D-Weekday-50-SDoff  20180518               2
130         125-D-Weekday-50-SDoff  20180521               2
131         125-D-Weekday-50-SDoff  20180522               2
132         125-D-Weekday-50-SDoff  20180523               2
133         125-D-Weekday-50-SDoff  20180524               2
134         125-D-Weekday-50-SDoff  20180525               2
135         125-D-Weekday-50-SDoff  20180529               2
136         125-D-Weekday-50-SDoff  20180530               2
137         125-D-Weekday-50-SDoff  20180531               2
138         125-D-Weekday-50-SDoff  20180601               2
139         125-D-Weekday-50-SDoff  20180604               2
140         125-D-Weekday-50-SDoff  20180605               2
141         125-D-Weekday-50-SDoff  20180606               2
142         125-D-Weekday-50-SDoff  20180607               2
143         125-D-Weekday-50-SDoff  20180608               2
144         125-D-Weekday-50-SDoff  20180611               2
145         125-D-Weekday-50-SDoff  20180612               2
146         125-D-Weekday-50-SDoff  20180613               2
147         125-D-Weekday-50-SDoff  20180614               2
148         125-D-Weekday-50-SDoff  20180615               2
149                125-D-Sunday-50  20180528               1

[150 rows x 3 columns]

In [24]:
filepath = files[6]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/stop_times.txt

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type
0,9898121-125-A-Weekday-50,10:04:00,10:04:00,315608,1,0,0
1,9898121-125-A-Weekday-50,10:06:00,10:06:00,315010,2,0,0
2,9898121-125-A-Weekday-50,10:06:00,10:06:00,315003,3,0,0
3,9898121-125-A-Weekday-50,10:07:00,10:07:00,315012,4,0,0
4,9898121-125-A-Weekday-50,10:09:00,10:09:00,315035,5,0,0
5,9898121-125-A-Weekday-50,10:10:00,10:10:00,315034,6,0,0
6,9898121-125-A-Weekday-50,10:10:00,10:10:00,315033,7,0,0
7,9898121-125-A-Weekday-50,10:11:00,10:11:00,315036,8,0,0
8,9898121-125-A-Weekday-50,10:12:00,10:12:00,315039,9,0,0
9,9898121-125-A-Weekday-50,10:13:00,10:13:00,315617,10,0,0
10,9898121-125-A-Weekday-50,10:16:00,10:16:00,315614,11,0,0
11,9898121-125-A-Weekday-50,10:18:00,10:18:00,315025,12,0,0
12,9898121-125-A-Weekday-50,10:21:00,10:21:00,315040,13,0,0
13,9898121-125-A-Weekday-50,10:22:00,10:22:00,315022,14,0,0
14,9898121-125-A-Weekday-50,10:22:00,10:22:00,315006,15,0,0
15,9898121-125-A-Weekday-50,10:23:00,10:23:00,315019,16,0,0
16,9898121-125-A-Weekday-50,10:24:00,10:24:00,315018,17,0,0
17,9898121-125-A-Weekday-50,10:25:00,10:25:00,315609,18,0,0
18,9898121-125-A-Weekday-50,10:25:00,10:25:00,315015,19,0,0
19,9898121-125-A-Weekday-50,10:26:00,10:26:00,315002,20,0,0
20,9898121-125-A-Weekday-50,10:27:00,10:27:00,314016,21,0,0
21,9898121-125-A-Weekday-50,10:28:00,10:28:00,314012,22,0,0
22,9898121-125-A-Weekday-50,10:29:00,10:29:00,314010,23,0,0
23,9898121-125-A-Weekday-50,10:29:00,10:29:00,314003,24,0,0
24,9898121-125-A-Weekday-50,10:29:00,10:29:00,314004,25,0,0
25,9898121-125-A-Weekday-50,10:30:00,10:30:00,314002,26,0,0
26,9898121-125-A-Weekday-50,10:30:00,10:30:00,314901,27,0,0
27,9898121-125-A-Weekday-50,10:31:00,10:31:00,314902,28,0,0
28,9898121-125-A-Weekday-50,10:32:00,10:32:00,313609,29,0,0
29,9898121-125-A-Weekday-50,10:34:00,10:34:00,313011,30,0,0
...,...,...,...,...,...,...,...
149316,9917812-125-D-Sunday-50,19:14:00,19:14:00,332556,30,0,0
149317,9917812-125-D-Sunday-50,19:14:00,19:14:00,332526,31,0,0
149318,9917812-125-D-Sunday-50,19:15:00,19:15:00,332518,32,0,0
149319,9917812-125-D-Sunday-50,19:17:00,19:17:00,332184,33,0,0
149320,9917812-125-D-Sunday-50,19:19:00,19:19:00,332602,34,0,0
149321,9917812-125-D-Sunday-50,19:20:00,19:20:00,332603,35,0,0
149322,9917812-125-D-Sunday-50,19:23:00,19:23:00,332019,36,0,0
149323,9917812-125-D-Sunday-50,19:26:00,19:26:00,332544,37,0,0
149324,9917812-125-D-Sunday-50,19:27:00,19:27:00,332218,38,0,0
149325,9917812-125-D-Sunday-50,19:27:00,19:27:00,332221,39,0,0
149326,9917812-125-D-Sunday-50,19:29:00,19:29:00,332348,40,0,0
149327,9917812-125-D-Sunday-50,19:29:00,19:29:00,332349,41,0,0
149328,9917812-125-D-Sunday-50,19:30:00,19:30:00,332032,42,0,0
149329,9917812-125-D-Sunday-50,19:31:00,19:31:00,332042,43,0,0
149330,9917812-125-D-Sunday-50,19:32:00,19:32:00,332006,44,0,0
149331,9917812-125-D-Sunday-50,19:33:00,19:33:00,332038,45,0,0
149332,9917812-125-D-Sunday-50,19:33:00,19:33:00,332046,46,0,0
149333,9918203-125-D-Sunday-50,18:39:00,18:39:00,333510,1,0,0
149334,9918203-125-D-Sunday-50,18:51:00,18:51:00,334611,2,0,0
149335,9918204-125-D-Sunday-50,07:06:00,07:06:00,334612,1,0,0
149336,9918204-125-D-Sunday-50,07:14:00,07:14:00,334008,2,0,0
149337,9918205-125-D-Sunday-50,17:48:00,17:48:00,333510,1,0,0
149338,9918205-125-D-Sunday-50,18:00:00,18:00:00,334611,2,0,0
149339,9918206-125-D-Sunday-50,06:51:00,06:51:00,334612,1,0,0
149340,9918206-125-D-Sunday-50,06:59:00,06:59:00,334008,2,0,0
149341,9918207-125-D-Sunday-50,07:00:00,07:00:00,334612,1,0,0
149342,9918207-125-D-Sunday-50,07:12:00,07:12:00,333510,2,0,0
149343,9918208-125-D-Sunday-50,18:33:00,18:33:00,334008,1,0,0
149344,9918208-125-D-Sunday-50,18:38:00,18:38:00,334011,2,0,0
149345,9918208-125-D-Sunday-50,18:45:00,18:45:00,334611,3,0,0

In [25]:
filepath = files[7]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/shapes.txt

        shape_id  shape_pt_lat  shape_pt_lon  shape_pt_sequence
0         140083     37.593895   -122.476088              10001
1         140083     37.593841   -122.476036              10002
2         140083     37.593615   -122.475883              10003
3         140083     37.593371   -122.475773              10004
4         140083     37.592087   -122.475615              10005
5         140083     37.591557   -122.475584              10006
6         140083     37.591465   -122.475595              10007
7         140083     37.591276   -122.475641              10008
8         140083     37.591189   -122.475675              10009
9         140083     37.590178   -122.476166              10010
10        140083     37.589700   -122.476462              10011
11        140083     37.589231   -122.476803              10012
12        140083     37.588730   -122.477133              10013
13        140083     37.588358   -122.477302              10014
14        140083     37.588154   -122.477355              10015
15        140083     37.587885   -122.477400              10016
16        140083     37.587631   -122.477392              10017
17        140083     37.587631   -122.477392              20001
18        140083     37.587426   -122.477385              20002
19        140083     37.587322   -122.477382              20003
20        140083     37.587099   -122.477341              20004
21        140083     37.586740   -122.477239              20005
22        140083     37.586496   -122.477138              20006
23        140083     37.585966   -122.476806              20007
24        140083     37.585637   -122.476587              20008
25        140083     37.585637   -122.476587              30001
26        140083     37.585376   -122.476412              30002
27        140083     37.584924   -122.476037              30003
28        140083     37.584861   -122.475971              30004
29        140083     37.584388   -122.475485              30005
...          ...           ...           ...                ...
117568  SMCS0005     37.572135   -122.332446             140004
117569  SMCS0005     37.571989   -122.332277             140005
117570  SMCS0005     37.571989   -122.332277             150001
117571  SMCS0005     37.571367   -122.331555             150002
117572  SMCS0005     37.570904   -122.331038             150003
117573  SMCS0005     37.570801   -122.330924             150004
117574  SMCS0005     37.570801   -122.330924             160001
117575  SMCS0005     37.569632   -122.329619             160002
117576  SMCS0005     37.568976   -122.328894             160003
117577  SMCS0005     37.568522   -122.328401             160004
117578  SMCS0005     37.568285   -122.328126             160005
117579  SMCS0005     37.568157   -122.327987             160006
117580  SMCS0005     37.568157   -122.327987             170001
117581  SMCS0005     37.567304   -122.327053             170002
117582  SMCS0005     37.566595   -122.326302             170003
117583  SMCS0005     37.566546   -122.326250             170004
117584  SMCS0005     37.566208   -122.325896             170005
117585  SMCS0005     37.566024   -122.325717             170006
117586  SMCS0005     37.566024   -122.325717             180001
117587  SMCS0005     37.565565   -122.325270             180002
117588  SMCS0005     37.565328   -122.325056             180003
117589  SMCS0005     37.565210   -122.324965             180004
117590  SMCS0005     37.565111   -122.324905             180005
117591  SMCS0005     37.565221   -122.324771             180006
117592  SMCS0005     37.565317   -122.324632             180007
117593  SMCS0005     37.565765   -122.323984             180008
117594  SMCS0005     37.566279   -122.323241             180009
117595  SMCS0005     37.566621   -122.323638             180010
117596  SMCS0005     37.567062   -122.324113             180011
117597  SMCS0005     37.567267   -122.323786             180012

[117598 rows x 4 columns]

In [26]:
filepath = files[8]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/trips.txt

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id
0,17-158,125-A-Weekday-50,9898121-125-A-Weekday-50,Linda Mar Park & Ride,171012,0,NaN,170521
1,17-158,125-A-Weekday-50,9898122-125-A-Weekday-50,Linda Mar Park & Ride,171010,0,NaN,170520
2,17-158,125-A-Weekday-50,9898123-125-A-Weekday-50,Linda Mar Park & Ride,171008,0,NaN,170521
3,17-158,125-A-Weekday-50,9898124-125-A-Weekday-50,Linda Mar Park & Ride,171002,0,NaN,170522
4,17-158,125-A-Weekday-50,9898125-125-A-Weekday-50,Linda Mar Park & Ride,171006,0,NaN,170523
5,17-158,125-A-Weekday-50,9898126-125-A-Weekday-50,Linda Mar Park & Ride,171014,0,NaN,170520
6,17-158,125-A-Weekday-50,9898127-125-A-Weekday-50,Linda Mar Park & Ride,171004,0,NaN,170521
7,17-158,125-A-Weekday-50,9898128-125-A-Weekday-50,Linda Mar Park & Ride,171022,0,NaN,170515
8,17-158,125-A-Weekday-50,9898129-125-A-Weekday-50,Linda Mar Park & Ride,171030,0,NaN,170524
9,17-158,125-A-Weekday-50,9898130-125-A-Weekday-50,Linda Mar Park & Ride,171032,0,NaN,170516
10,17-158,125-A-Weekday-50,9898131-125-A-Weekday-50,Linda Mar Park & Ride,171016,0,NaN,170516
11,17-158,125-A-Weekday-50,9898132-125-A-Weekday-50,Linda Mar Park & Ride,171026,0,NaN,170515
12,17-158,125-A-Weekday-50,9898133-125-A-Weekday-50,Moonridge Apts,171027,1,NaN,170517
13,17-158,125-A-Weekday-50,9898134-125-A-Weekday-50,Moonridge Apts,171031,1,NaN,170517
14,17-158,125-A-Weekday-50,9898135-125-A-Weekday-50,Pescadero,171025,1,NaN,170519
15,17-158,125-A-Weekday-50,9898136-125-A-Weekday-50,Moonridge Apts,171029,1,NaN,170517
16,17-158,125-A-Weekday-50,9898137-125-A-Weekday-50,Moonridge Apts,171015,1,NaN,170518
17,17-158,125-A-Weekday-50,9898138-125-A-Weekday-50,Moonridge Apts,171019,1,NaN,170518
18,17-158,125-A-Weekday-50,9898139-125-A-Weekday-50,Moonridge Apts,171021,1,NaN,170517
19,17-158,125-A-Weekday-50,9898140-125-A-Weekday-50,Moonridge Apts,171023,1,NaN,170518
20,17-158,125-A-Weekday-50,9898141-125-A-Weekday-50,Moonridge Apts,171017,1,NaN,170517
21,FLXP-158,125-A-Weekday-50,9898142-125-A-Weekday-50,Pacifica,2201001,0,NaN,FLXP0055
22,FLXP-158,125-A-Weekday-50,9898143-125-A-Weekday-50,Pacifica,2201003,0,NaN,FLXP0055
23,FLXP-158,125-A-Weekday-50,9898144-125-A-Weekday-50,Pacifica,2201005,0,NaN,FLXP0055
24,FLXP-158,125-A-Weekday-50,9898145-125-A-Weekday-50,Pacifica,2201007,0,NaN,FLXP0055
25,FLXP-158,125-A-Weekday-50,9898146-125-A-Weekday-50,Pacifica,2201009,0,NaN,FLXP0055
26,FLXP-158,125-A-Weekday-50,9898147-125-A-Weekday-50,Pacifica,2201011,0,NaN,FLXP0055
27,FLXP-158,125-A-Weekday-50,9898148-125-A-Weekday-50,Pacifica,2201013,0,NaN,FLXP0055
28,FLXP-158,125-A-Weekday-50,9898149-125-A-Weekday-50,Pacifica,2201015,0,NaN,FLXP0055
29,FLXP-158,125-A-Weekday-50,9898150-125-A-Weekday-50,Pacifica,2201017,0,NaN,FLXP0055
...,...,...,...,...,...,...,...,...
3458,280-158,125-D-Sunday-50,9917789-125-D-Sunday-50,Purdue/Fordham,2807016,0,NaN,2800178
3459,281-158,125-D-Sunday-50,9917790-125-D-Sunday-50,Onetta Harris Center,2817028,0,NaN,2810216
3460,281-158,125-D-Sunday-50,9917791-125-D-Sunday-50,Onetta Harris Center,2817030,0,NaN,2810216
3461,280-158,125-D-Sunday-50,9917792-125-D-Sunday-50,Purdue/Fordham,2807018,0,NaN,2800178
3462,281-158,125-D-Sunday-50,9917793-125-D-Sunday-50,Onetta Harris Center,2817032,0,NaN,2810216
3463,281-158,125-D-Sunday-50,9917794-125-D-Sunday-50,Onetta Harris Center,2817034,0,NaN,2810216
3464,280-158,125-D-Sunday-50,9917795-125-D-Sunday-50,Purdue/Fordham,2807020,0,NaN,2800178
3465,281-158,125-D-Sunday-50,9917796-125-D-Sunday-50,Onetta Harris Center,2817036,0,NaN,2810216
3466,281-158,125-D-Sunday-50,9917797-125-D-Sunday-50,Onetta Harris Center,2817038,0,NaN,2810216
3467,280-158,125-D-Sunday-50,9917798-125-D-Sunday-50,Purdue/Fordham,2807022,0,NaN,2800178
3468,281-158,125-D-Sunday-50,9917799-125-D-Sunday-50,Onetta Harris Center,2817040,0,NaN,2810216
3469,280-158,125-D-Sunday-50,9917800-125-D-Sunday-50,Purdue/Fordham,2807024,0,NaN,2800178
3470,121-158,125-D-Sunday-50,9917801-125-D-Sunday-50,Pope/Bellevue,1217002,0,NaN,1210280
3471,121-158,125-D-Sunday-50,9917802-125-D-Sunday-50,Pope/Bellevue,1217004,0,NaN,1210280
3472,121-158,125-D-Sunday-50,9917803-125-D-Sunday-50,Pope/Bellevue,1217006,0,NaN,1210280
3473,121-158,125-D-Sunday-50,9917804-125-D-Sunday-50,Pope/Bellevue,1217008,0,NaN,1210280
3474,121-158,125-D-Sunday-50,9917805-125-D-Sunday-50,Pope/Bellevue,1217010,0,NaN,1210280
3475,121-158,125-D-Sunday-50,9917806-125-D-Sunday-50,Pope/Bellevue,1217012,0,NaN,1210280
3476,121-158,125-D-Sunday-50,9917807-125-D-Sunday-50,Pope/Bellevue,1217014,0,NaN,1210280
3477,121-158,125-D-Sunday-50,9917808-125-D-Sunday-50,Pope/Bellevue,1217016,0,NaN,1210280
3478,121-158,125-D-Sunday-50,9917809-125-D-Sunday-50,Pope/Bellevue,1217018,0,NaN,1210280
3479,121-158,125-D-Sunday-50,9917810-125-D-Sunday-50,Pope/Bellevue,1217020,0,NaN,1210280
3480,121-158,125-D-Sunday-50,9917811-125-D-Sunday-50,Pope/Bellevue,1217022,0,NaN,1210280
3481,121-158,125-D-Sunday-50,9917812-125-D-Sunday-50,Pope/Bellevue,1217024,0,NaN,1210280
3482,38-158,125-D-Sunday-50,9918203-125-D-Sunday-50,Safe Harbor,387005,0,NaN,380071
3483,38-158,125-D-Sunday-50,9918204-125-D-Sunday-50,Airport/Linden,387006,1,NaN,380070
3484,38-158,125-D-Sunday-50,9918205-125-D-Sunday-50,Safe Harbor,387001,0,NaN,380071
3485,38-158,125-D-Sunday-50,9918206-125-D-Sunday-50,Airport/Linden,387002,1,NaN,380070
3486,38-158,125-D-Sunday-50,9918207-125-D-Sunday-50,Colma BART,387004,1,NaN,380069
3487,38-158,125-D-Sunday-50,9918208-125-D-Sunday-50,Safe Harbor,387003,0,NaN,380072

In [27]:
filepath = files[9]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/stops.txt

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station
0,311010,311010,Terra Nova Blvd & Alicante Dr,NaN,37.585609,-122.476654,1,NaN,0,NaN
1,311013,311013,Bradford Way & Fairway Dr,NaN,37.621694,-122.485818,1,NaN,0,NaN
2,311016,311016,Capistrano Dr & Linda Mar Blvd,NaN,37.582440,-122.483578,1,NaN,0,NaN
3,311018,311018,Capistrano Dr & Rosita Rd,NaN,37.581126,-122.483647,1,NaN,0,NaN
4,311019,311019,Clarendon Rd & Francisco Blvd,NaN,37.629827,-122.489951,1,NaN,0,NaN
5,311020,311020,Clarendon Rd & Francisco Blvd,NaN,37.629935,-122.490219,1,NaN,0,NaN
6,311022,311022,1159 Crespi Dr,NaN,37.589334,-122.487106,1,NaN,0,NaN
7,311023,311023,Crespi Dr & Alcala Ct,NaN,37.591192,-122.489231,1,NaN,0,NaN
8,311024,311024,Crespi Dr & Barcelona Dr,NaN,37.592438,-122.488469,1,NaN,0,NaN
9,311025,311025,Crespi Dr & De Solo Dr,NaN,37.595272,-122.497519,1,NaN,0,NaN
10,311026,311026,Crespi Dr & Seville Dr,NaN,37.593491,-122.492214,1,NaN,0,NaN
11,311027,311027,Crespi Dr & Escalero Ave,NaN,37.593645,-122.492489,1,NaN,0,NaN
12,311028,311028,Crespi Dr & Fassler Ave,NaN,37.598818,-122.482677,1,NaN,0,NaN
13,311029,311029,Crespi Dr & Fassler Ave,NaN,37.598728,-122.482538,1,NaN,0,NaN
14,311030,311030,Crespi Dr & Hwy 1,NaN,37.598951,-122.499371,1,NaN,0,NaN
15,311032,311032,Crespi Dr & Ladera Way,NaN,37.596613,-122.496897,1,NaN,0,NaN
16,311033,311033,Crespi Dr & Lerida Way,NaN,37.594239,-122.480986,1,NaN,0,NaN
17,311034,311034,Crespi Dr & Lerida Way,NaN,37.594293,-122.480849,1,NaN,0,NaN
18,311035,311035,Crespi Dr & Manzanita Dr,NaN,37.589688,-122.484194,1,NaN,0,NaN
19,311036,311036,Crespi Dr & Manzanita Dr,NaN,37.589661,-122.484380,1,NaN,0,NaN
20,311037,311037,Crespi Dr & Peralta Rd,NaN,37.593325,-122.495750,1,NaN,0,NaN
21,311038,311038,Crespi Dr & Peralta Rd,NaN,37.593324,-122.496091,1,NaN,0,NaN
22,311039,311039,Crespi Dr & Regina Way,NaN,37.593406,-122.488870,1,NaN,0,NaN
23,311040,311040,Crespi Dr & Roberts Rd,NaN,37.598040,-122.498012,1,NaN,0,NaN
24,311041,311041,Crespi Dr & Roberts Rd,NaN,37.598241,-122.497991,1,NaN,0,NaN
25,311042,311042,Crespi Dr & Tapis Way,NaN,37.589759,-122.488455,1,NaN,0,NaN
26,311043,311043,De Solo Dr & Anza Dr,NaN,37.595982,-122.498681,1,NaN,0,NaN
27,311049,311049,Francisco Blvd & Lakeside Ave,NaN,37.628538,-122.489777,1,NaN,0,NaN
28,311050,311050,Gateway Dr & Eastridge Cir,NaN,37.664568,-122.482055,1,NaN,0,NaN
29,311051,311051,Gateway Dr & Eastridge Cir,NaN,37.664629,-122.482516,1,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...
1916,363054,363054,Pulgas Ave & Sage St,NaN,37.464108,-122.130085,1,NaN,0,NaN
1917,363055,363055,Purdue Ave & Fordham St,NaN,37.478131,-122.136781,1,NaN,0,NaN
1918,363060,363060,University Ave & Donohoe St,NaN,37.463657,-122.141604,1,NaN,0,NaN
1919,363062,363062,University Ave & Bell St,NaN,37.465892,-122.141451,1,NaN,0,NaN
1920,363063,363063,University Ave & Bell St,NaN,37.466320,-122.141693,1,NaN,0,NaN
1921,363064,363064,2111 University Ave-Bell St Park,NaN,37.463668,-122.141855,1,NaN,0,NaN
1922,363065,363065,University Ave & Runnymede St,NaN,37.468254,-122.141585,1,NaN,0,NaN
1923,363066,363066,University Ave & Runnymede St,NaN,37.468747,-122.141153,1,NaN,0,NaN
1924,363067,363067,University Ave & Sacramento St,NaN,37.469834,-122.140746,1,NaN,0,NaN
1925,363068,363068,University Ave & Woodland Ave,NaN,37.457710,-122.142116,1,NaN,0,NaN
1926,363074,363074,University Ave & Woodland Ave,NaN,37.457621,-122.141931,1,NaN,0,NaN
1927,363080,363080,Bay Rd & University Ave Farside,NaN,37.471589,-122.139024,1,NaN,0,NaN
1928,363101,363101,East Okeefe St & Menalto Ave,NaN,37.462227,-122.149472,1,NaN,0,NaN
1929,363102,363102,East Okeefe St & Menalto Ave,NaN,37.462300,-122.149159,1,NaN,0,NaN
1930,363103,363103,East Okeefe St & Euclid Ave,NaN,37.461643,-122.145316,1,NaN,0,NaN
1931,363104,363104,East Okeefe St & Euclid Ave,NaN,37.461796,-122.145588,1,NaN,0,NaN
1932,363600,363600,E Bayshore Rd & Donohoe St,NaN,37.461224,-122.137964,1,NaN,0,NaN
1933,363601,363601,Bay Rd & Clarke Ave,NaN,37.471635,-122.135317,1,NaN,0,NaN
1934,363602,363602,Bay Rd & Pulgas Ave,NaN,37.472706,-122.132073,1,NaN,0,NaN
1935,363604,363604,Pulgas Ave & Weeks St,NaN,37.470450,-122.130373,1,NaN,0,NaN
1936,363605,363605,Bay Rd & Pulgas Ave,NaN,37.472747,-122.132640,1,NaN,0,NaN
1937,363606,363606,Bay Rd & Clarke Ave,NaN,37.471853,-122.135518,1,NaN,0,NaN
1938,363607,363607,Pulgas Ave & Weeks St,NaN,37.469789,-122.130381,1,NaN,0,NaN
1939,363608,363608,Clarke Ave & Runnymede St,NaN,37.468068,-122.134771,1,NaN,0,NaN
1940,363609,363609,Clarke Ave & Runnymede St,NaN,37.468092,-122.134957,1,NaN,0,NaN
1941,363610,363610,Woodland Ave & Manhattan Ave,NaN,37.458322,-122.143543,1,NaN,0,NaN
1942,363611,363611,Pulgas Ave & Garden St,NaN,37.466424,-122.130290,1,NaN,0,NaN
1943,363612,363612,Pulgas Ave & Garden St,NaN,37.467304,-122.130157,1,NaN,0,NaN
1944,363613,363613,Clarke Ave & Donohoe St,NaN,37.462741,-122.134755,1,NaN,0,NaN
1945,615001,615001,Main St & Hwy 92,NaN,37.467114,-122.429615,1,NaN,0,NaN

In [28]:
filepath = files[10]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/realtime_trips.txt

                       trip_id  realtime_trip_id
0     9898121-125-A-Weekday-50            171012
1     9898122-125-A-Weekday-50            171010
2     9898123-125-A-Weekday-50            171008
3     9898124-125-A-Weekday-50            171002
4     9898125-125-A-Weekday-50            171006
5     9898126-125-A-Weekday-50            171014
6     9898127-125-A-Weekday-50            171004
7     9898128-125-A-Weekday-50            171022
8     9898129-125-A-Weekday-50            171030
9     9898130-125-A-Weekday-50            171032
10    9898131-125-A-Weekday-50            171016
11    9898132-125-A-Weekday-50            171026
12    9898133-125-A-Weekday-50            171027
13    9898134-125-A-Weekday-50            171031
14    9898135-125-A-Weekday-50            171025
15    9898136-125-A-Weekday-50            171029
16    9898137-125-A-Weekday-50            171015
17    9898138-125-A-Weekday-50            171019
18    9898139-125-A-Weekday-50            171021
19    9898140-125-A-Weekday-50            171023
20    9898141-125-A-Weekday-50            171017
21    9898142-125-A-Weekday-50           2201001
22    9898143-125-A-Weekday-50           2201003
23    9898144-125-A-Weekday-50           2201005
24    9898145-125-A-Weekday-50           2201007
25    9898146-125-A-Weekday-50           2201009
26    9898147-125-A-Weekday-50           2201011
27    9898148-125-A-Weekday-50           2201013
28    9898149-125-A-Weekday-50           2201015
29    9898150-125-A-Weekday-50           2201017
...                        ...               ...
3458   9917789-125-D-Sunday-50           2807016
3459   9917790-125-D-Sunday-50           2817028
3460   9917791-125-D-Sunday-50           2817030
3461   9917792-125-D-Sunday-50           2807018
3462   9917793-125-D-Sunday-50           2817032
3463   9917794-125-D-Sunday-50           2817034
3464   9917795-125-D-Sunday-50           2807020
3465   9917796-125-D-Sunday-50           2817036
3466   9917797-125-D-Sunday-50           2817038
3467   9917798-125-D-Sunday-50           2807022
3468   9917799-125-D-Sunday-50           2817040
3469   9917800-125-D-Sunday-50           2807024
3470   9917801-125-D-Sunday-50           1217002
3471   9917802-125-D-Sunday-50           1217004
3472   9917803-125-D-Sunday-50           1217006
3473   9917804-125-D-Sunday-50           1217008
3474   9917805-125-D-Sunday-50           1217010
3475   9917806-125-D-Sunday-50           1217012
3476   9917807-125-D-Sunday-50           1217014
3477   9917808-125-D-Sunday-50           1217016
3478   9917809-125-D-Sunday-50           1217018
3479   9917810-125-D-Sunday-50           1217020
3480   9917811-125-D-Sunday-50           1217022
3481   9917812-125-D-Sunday-50           1217024
3482   9918203-125-D-Sunday-50            387005
3483   9918204-125-D-Sunday-50            387006
3484   9918205-125-D-Sunday-50            387001
3485   9918206-125-D-Sunday-50            387002
3486   9918207-125-D-Sunday-50            387004
3487   9918208-125-D-Sunday-50            387003

[3488 rows x 2 columns]

In [29]:
filepath = files[11]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/calendar_attributes.txt

                       service_id service_description
0                125-A-Weekday-50             Weekday
1           125-A-Weekday-50-SDon             Weekday
2   125-A-Weekday-50-SDon-1110100     Mon Tue Wed Fri
3   125-A-Weekday-50-SDon-0101000             Tue Thu
4               125-A-Saturday-50            Saturday
5                 125-A-Sunday-50              Sunday
6                125-C-Weekday-50             Weekday
7           125-C-Weekday-50-SDon             Weekday
8   125-C-Weekday-50-SDon-0010000                 Wed
9   125-C-Weekday-50-SDon-1110100     Mon Tue Wed Fri
10  125-C-Weekday-50-SDon-0011000             Wed Thu
11  125-C-Weekday-50-SDon-1101100     Mon Tue Thu Fri
12  125-C-Weekday-50-SDon-0100000                 Tue
13  125-C-Weekday-50-SDon-1100100         Mon Tue Fri
14  125-C-Weekday-50-SDon-1011100     Mon Wed Thu Fri
15              125-C-Saturday-50            Saturday
16                125-C-Sunday-50              Sunday
17               125-D-Weekday-50             Weekday
18          125-D-Weekday-50-SDon             Weekday
19         125-D-Weekday-50-SDoff             Weekday
20  125-D-Weekday-50-SDon-1110100     Mon Tue Wed Fri
21  125-D-Weekday-50-SDon-1101100     Mon Tue Thu Fri
22  125-D-Weekday-50-SDon-0001000                 Thu
23  125-D-Weekday-50-SDon-0010000                 Wed
24  125-D-Weekday-50-SDon-0011000             Wed Thu
25  125-D-Weekday-50-SDon-1100100         Mon Tue Fri
26  125-D-Weekday-50-SDon-1011100     Mon Wed Thu Fri
27  125-D-Weekday-50-SDon-0100000                 Tue
28              125-D-Saturday-50            Saturday
29                125-D-Sunday-50              Sunday

In [30]:
filepath = files[12]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/realtime_routes.txt

    route_id  realtime_enabled  realtime_routename  realtime_routecode
0     14-158                 1                 NaN                 NaN
1     16-158                 1                 NaN                 NaN
2     17-158                 1                 NaN                 NaN
3     18-158                 1                 NaN                 NaN
4     19-158                 1                 NaN                 NaN
5     24-158                 1                 NaN                 NaN
6     25-158                 1                 NaN                 NaN
7     28-158                 1                 NaN                 NaN
8     29-158                 1                 NaN                 NaN
9     35-158                 1                 NaN                 NaN
10    37-158                 1                 NaN                 NaN
11    38-158                 1                 NaN                 NaN
12    39-158                 1                 NaN                 NaN
13    46-158                 1                 NaN                 NaN
14    49-158                 1                 NaN                 NaN
15    53-158                 1                 NaN                 NaN
16    54-158                 1                 NaN                 NaN
17    55-158                 1                 NaN                 NaN
18    56-158                 1                 NaN                 NaN
19    57-158                 1                 NaN                 NaN
20    58-158                 1                 NaN                 NaN
21    59-158                 1                 NaN                 NaN
22    60-158                 1                 NaN                 NaN
23    61-158                 1                 NaN                 NaN
24    62-158                 1                 NaN                 NaN
25    67-158                 1                 NaN                 NaN
26    68-158                 1                 NaN                 NaN
27    72-158                 1                 NaN                 NaN
28    73-158                 1                 NaN                 NaN
29    78-158                 1                 NaN                 NaN
..       ...               ...                 ...                 ...
42   118-158                 1                 NaN                 NaN
43   120-158                 1                 NaN                 NaN
44   121-158                 1                 NaN                 NaN
45   122-158                 1                 NaN                 NaN
46   130-158                 1                 NaN                 NaN
47   140-158                 1                 NaN                 NaN
48   141-158                 1                 NaN                 NaN
49   250-158                 1                 NaN                 NaN
50   251-158                 1                 NaN                 NaN
51   256-158                 1                 NaN                 NaN
52   260-158                 1                 NaN                 NaN
53   270-158                 1                 NaN                 NaN
54   274-158                 1                 NaN                 NaN
55   275-158                 1                 NaN                 NaN
56   276-158                 1                 NaN                 NaN
57   278-158                 1                 NaN                 NaN
58   280-158                 1                 NaN                 NaN
59   281-158                 1                 NaN                 NaN
60   286-158                 1                 NaN                 NaN
61   292-158                 1                 NaN                 NaN
62   294-158                 1                 NaN                 NaN
63   295-158                 1                 NaN                 NaN
64   296-158                 1                 NaN                 NaN
65   397-158                 1                 NaN                 NaN
66   398-158                 1                 NaN                 NaN
67   399-158                 1                 NaN                 NaN
68   ECR-158                 1                 NaN                 NaN
69  FLXP-158                 1                 NaN                 NaN
70    KX-158                 1                 NaN                 NaN
71  SMCS-158                 1                 NaN                 NaN

[72 rows x 4 columns]

In [31]:
filepath = files[13]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/calendar.txt

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,125-A-Weekday-50,1,1,1,1,1,0,0,20180122,20180615
1,125-A-Weekday-50-SDon,1,1,1,1,1,0,0,20180122,20180615
2,125-A-Weekday-50-SDon-1110100,1,1,1,0,1,0,0,20180122,20180615
3,125-A-Weekday-50-SDon-0101000,0,1,0,1,0,0,0,20180122,20180615
4,125-A-Saturday-50,0,0,0,0,0,1,0,20180127,20180616
5,125-A-Sunday-50,0,0,0,0,0,0,1,20180121,20180610
6,125-C-Weekday-50,1,1,1,1,1,0,0,20180122,20180615
7,125-C-Weekday-50-SDon,1,1,1,1,1,0,0,20180122,20180615
8,125-C-Weekday-50-SDon-0010000,0,0,1,0,0,0,0,20180122,20180615
9,125-C-Weekday-50-SDon-1110100,1,1,1,0,1,0,0,20180122,20180615
10,125-C-Weekday-50-SDon-0011000,0,0,1,1,0,0,0,20180122,20180615
11,125-C-Weekday-50-SDon-1101100,1,1,0,1,1,0,0,20180122,20180615
12,125-C-Weekday-50-SDon-0100000,0,1,0,0,0,0,0,20180122,20180615
13,125-C-Weekday-50-SDon-1100100,1,1,0,0,1,0,0,20180122,20180615
14,125-C-Weekday-50-SDon-1011100,1,0,1,1,1,0,0,20180122,20180615
15,125-C-Saturday-50,0,0,0,0,0,1,0,20180127,20180616
16,125-C-Sunday-50,0,0,0,0,0,0,1,20180121,20180610
17,125-D-Weekday-50,1,1,1,1,1,0,0,20180122,20180615
18,125-D-Weekday-50-SDon,1,1,1,1,1,0,0,20180122,20180615
19,125-D-Weekday-50-SDoff,1,1,1,1,1,0,0,20180122,20180615
20,125-D-Weekday-50-SDon-1110100,1,1,1,0,1,0,0,20180122,20180615
21,125-D-Weekday-50-SDon-1101100,1,1,0,1,1,0,0,20180122,20180615
22,125-D-Weekday-50-SDon-0001000,0,0,0,1,0,0,0,20180122,20180615
23,125-D-Weekday-50-SDon-0010000,0,0,1,0,0,0,0,20180122,20180615
24,125-D-Weekday-50-SDon-0011000,0,0,1,1,0,0,0,20180122,20180615
25,125-D-Weekday-50-SDon-1100100,1,1,0,0,1,0,0,20180122,20180615
26,125-D-Weekday-50-SDon-1011100,1,0,1,1,1,0,0,20180122,20180615
27,125-D-Weekday-50-SDon-0100000,0,1,0,0,0,0,0,20180122,20180615
28,125-D-Saturday-50,0,0,0,0,0,1,0,20180127,20180616
29,125-D-Sunday-50,0,0,0,0,0,0,1,20180121,20180610

In [32]:
filepath = files[14]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/realtime_directions.txt

,trip_id,direction_id,Direction,realtime_directioncode
0,9898121-125-A-Weekday-50,0,North,171012
1,9898133-125-A-Weekday-50,1,South,171027
2,9898142-125-A-Weekday-50,0,Clockwise,2201001
3,9898193-125-A-Weekday-50-SDon,0,North,181006
4,9898194-125-A-Weekday-50-SDon,1,South,181009
5,9898216-125-A-Weekday-50,1,Counterclockwise,2521002
6,9898235-125-A-Saturday-50,0,North,176002
7,9898243-125-A-Saturday-50,1,South,176001
8,9898265-125-A-Sunday-50,0,North,177002
9,9898273-125-A-Sunday-50,1,South,177001
10,9920975-125-C-Weekday-50,1,South,2921067
11,9920976-125-C-Weekday-50,0,North,2041006
12,9920978-125-C-Weekday-50,1,South,1221057
13,9920979-125-C-Weekday-50,0,North,2921040
14,9920983-125-C-Weekday-50,1,South,2041007
15,9920986-125-C-Weekday-50-SDon,0,East,781002
16,9920987-125-C-Weekday-50-SDon,1,West,601005
17,9920989-125-C-Weekday-50,0,North,1221072
18,9920990-125-C-Weekday-50,1,South,2961021
19,9920991-125-C-Weekday-50,0,North,2961040
20,9921022-125-C-Weekday-50-SDon,1,West,841001
21,9921040-125-C-Weekday-50-SDon-1110100,1,West,571001
22,9921047-125-C-Weekday-50-SDon-0011000,0,East,2863008
23,9921049-125-C-Weekday-50-SDon-0011000,0,East,821002
24,9921070-125-C-Weekday-50-SDon,0,East,591002
25,9921075-125-C-Weekday-50-SDon-1110100,1,West,591003
26,9921118-125-C-Weekday-50-SDon-1101100,0,East,671014
27,9921125-125-C-Weekday-50-SDon-0010000,1,West,291001
28,9921160-125-C-Weekday-50-SDon,0,East,541002
29,9921177-125-C-Weekday-50-SDon-0010000,1,South,611003
...,...,...,...,...
228,9917267-125-D-Saturday-50,0,Inbound,386006
229,9917269-125-D-Saturday-50,1,Outbound,386003
230,9917286-125-D-Sunday-50,1,West,2507001
231,9917296-125-D-Sunday-50,0,North,1307002
232,9917297-125-D-Sunday-50,1,West,1417001
233,9917343-125-D-Sunday-50,1,West,1407001
234,9917354-125-D-Sunday-50,0,North,1207002
235,9917359-125-D-Sunday-50,1,South,1127001
236,9917413-125-D-Sunday-50,1,South,1107001
237,9917423-125-D-Sunday-50,1,South,4007005
238,9917427-125-D-Sunday-50,1,South,1307001
239,9917495-125-D-Sunday-50,1,South,3987001
240,9917496-125-D-Sunday-50,0,East,1417002
241,9917534-125-D-Sunday-50,1,South,1207001
242,9917583-125-D-Sunday-50,0,East,2507002
243,9917593-125-D-Sunday-50,0,East,2947004
244,9917608-125-D-Sunday-50,1,West,2817001
245,9917629-125-D-Sunday-50,0,North,4007006
246,9917679-125-D-Sunday-50,0,East,2807002
247,9917680-125-D-Sunday-50,0,East,1407002
248,9917691-125-D-Sunday-50,1,South,1217001
249,9917704-125-D-Sunday-50,0,North,1107002
250,9917706-125-D-Sunday-50,0,North,1127002
251,9917725-125-D-Sunday-50,1,West,2807001
252,9917737-125-D-Sunday-50,0,North,3987002
253,9917755-125-D-Sunday-50,1,West,2947003
254,9917770-125-D-Sunday-50,0,East,2817002
255,9917801-125-D-Sunday-50,0,North,1217002
256,9918203-125-D-Sunday-50,0,Inbound,387005
257,9918204-125-D-Sunday-50,1,Outbound,387006

In [33]:
filepath = files[15]

print(filepath)
dataframe = pandas.read_csv(filepath)

dataframe

../data/ST-GTFS/routes.txt

,route_id,route_short_name,route_long_name,route_desc,route_type,route_url
0,14-158,14,Linda Mar Circulator,NaN,3,NaN
1,16-158,16,Serramonte Center - Terra Nova High,NaN,3,NaN
2,17-158,17,Linda Mar Park & Ride - Pescadero,NaN,3,NaN
3,18-158,18,Main/7th - HMBHS - Moonridge Apts,NaN,3,NaN
4,19-158,19,Lacy School - Linda Mar Park & Ride,NaN,3,NaN
5,24-158,24,Brisbane - Westmoor High,NaN,3,NaN
6,25-158,25,Los Olivos/Santa Barbara - Ben Franklin School,NaN,3,NaN
7,28-158,28,Serramonte Center - South City High,NaN,3,NaN
8,29-158,29,Lipman School - Templeton/Brunswick,NaN,3,NaN
9,35-158,35,El Camino High - Warwick/Christen,NaN,3,NaN
10,37-158,37,Hillside/Grove - Alta Loma School,NaN,3,NaN
11,38-158,38,Safe Harbor Shelter,NaN,3,NaN
12,39-158,39,Alta Loma School - Hazelwood/Kenwood,NaN,3,NaN
13,46-158,46,Burlingame School - Carolan (Burlingame Caltrain),NaN,3,NaN
14,49-158,49,Airport/San Bruno - Terra Nova High,NaN,3,NaN
15,53-158,53,Peninsula/Humboldt - Borel MS,NaN,3,NaN
16,54-158,54,Bowditch School - Hillsdale/Norfolk,NaN,3,NaN
17,55-158,55,Clark/El Camino - Borel MS,NaN,3,NaN
18,56-158,56,Aragon HS - Polhemus/Paul Scannell,NaN,3,NaN
19,57-158,57,Edgewater/Beach Park - Hillsdale High,NaN,3,NaN
20,58-158,58,Borel School - Polhemus/Paul Scannell,NaN,3,NaN
21,59-158,59,Hillsdale/Norfolk - Aragon High,NaN,3,NaN
22,60-158,60,Ralston School - Bridge/Bowsprit via Chula Vista,NaN,3,NaN
23,61-158,61,San Carlos Caltrain - Alameda/Ralston,NaN,3,NaN
24,62-158,62,Hillsdale - Alameda & Ralston,NaN,3,NaN
25,67-158,67,Bridge/Bowsprit - Ralston School,NaN,3,NaN
26,68-158,68,Hiller/Wessex - Ralston School,NaN,3,NaN
27,72-158,72,Malborough/Dumbarton - Selby Lane School,NaN,3,NaN
28,73-158,73,"""G"" & Industrial - Clifford School",NaN,3,NaN
29,78-158,78,Woodside/Alameda - WHS,NaN,3,NaN
...,...,...,...,...,...,...
42,118-158,118,Linda Mar Park & Ride - Daly City BART,NaN,3,NaN
43,120-158,120,Colma BART - Brunswick/Templeton,NaN,3,NaN
44,121-158,121,Lowell/Hanover - Skyline College,NaN,3,NaN
45,122-158,122,South SF BART - Stonestown/SF State,NaN,3,NaN
46,130-158,130,Daly City BART - Airport/Linden,NaN,3,NaN
47,140-158,140,Airtrain - West Manor/Palmetto,NaN,3,NaN
48,141-158,141,Airport/Linden - Shelter Creek,NaN,3,NaN
49,250-158,250,5th/El Camino - College of San Mateo,NaN,3,NaN
50,251-158,251,Foster City - Hillsdale Mall,NaN,3,NaN
51,256-158,256,Hillsdale Mall - Foster City,NaN,3,NaN
52,260-158,260,San Carlos Caltrain - College of San Mateo,NaN,3,NaN
53,270-158,270,Redwood City Caltrain - Florence/17th loop,NaN,3,NaN
54,274-158,274,Redwood City Transit Ctr - Canada College,NaN,3,NaN
55,275-158,275,Redwood City Transit Ctr - Alameda/Woodside,NaN,3,NaN
56,276-158,276,Redwood City Transit Ctr - Florence/17th,NaN,3,NaN
57,278-158,278,Woodside/Alameda - Canada College - Saturday Only,NaN,3,NaN
58,280-158,280,Purdue/Fordham - Stanford Mall,NaN,3,NaN
59,281-158,281,Onetta Harris Ctr - Stanford Mall,NaN,3,NaN
60,286-158,286,Ringwood/Arlington - Monte Rosa/Eastridge,NaN,3,NaN
61,292-158,292,San Francisco - SFO - Hillsdale Mall,NaN,3,NaN
62,294-158,294,SM Med Ctr - Hillsdale - CSM - Half Moon Bay,NaN,3,NaN
63,295-158,295,San Mateo Caltrain - Redwood City Transit Center,NaN,3,NaN
64,296-158,296,Redwood City Transit Cente - Bayshore/Donohoe,NaN,3,NaN
65,397-158,397,San Francisco - Palo Alto Transit Ctr,NaN,3,NaN
66,398-158,398,San Bruno BART - Redwood City Transit Ctr,NaN,3,NaN
67,399-158,399,Daly City - SFO Airport Owl,NaN,3,NaN
68,ECR-158,ECR,Daly City BART - Palo Alto Transit Ctr,NaN,3,NaN
69,FLXP-158,FLX,Flex Route Pacifica,NaN,3,NaN
70,KX-158,KX,SF - SFO - Redwood City Transit Ctr EXPPRESS,NaN,3,NaN
71,SMCS-158,SMCS,San Mateo Connect Shuttle,NaN,3,NaN